### ISSUE TITLE
ShouldCompareDisruptorVsQueuesPublic hangs

### ISSUE THREAD

**Issue by nesteruk** [TimGebhardt/Disruptor.NET#3]
Tried running the tests, but the ShouldCompareDisruptorVsQueuesPublic test just hangs forever.

**Comment by TimGebhardt** [comment]
I haven't updated my GitHub repo, but I probably should.  I'm devoting my energy to the disruptor-net project on Google Code: https://code.google.com/p/disruptor-net

I suggest you check that you if you haven't seen it already.

**Comment by nesteruk** [comment]
Ahh, got it, seems to be good. BTW, most people will assume by default that the Github project is 'current' and the Google Code is a relic.
