### ISSUE TITLE
Sequencer3P1CDisriptorPerfTest hangs

### ISSUE THREAD

**Issue by nesteruk** [TimGebhardt/Disruptor.NET#4]
I've decided to run all of the Disruptor.NET tests, so I let it run and came back half an hour later to find that the `Sequencer3P1CDisriptorPerfTest` test was still running. I tried running it individually but it hang again. Just wondering if this is a possible bug. I'm using the ReSharper test runner.

**Comment by TimGebhardt** [comment]
Hi Dmitri,

Thanks for your interest.  Please see the readme for the project.  This
implementation of the disruptor pattern for .NET has been abandoned in
favor of joining forces with another.  You can find the link for the much
improved project there.

Tim

On Fri, Feb 17, 2012 at 2:53 AM, Dmitri Nesteruk <
reply@reply.github.com

**Comment by nesteruk** [comment]
Thanks, should have RTFM :)
